#!/bin/sh

#
# Copyright 2015 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell such as ksh or
#       bash, then to run this script, type that shell name before the whole
#       command line, like:
#
#           ksh Gradle
#
#       Busybox and similar reduced shells will NOT work, because this script
#       requires all of these POSIX shell features:
#         * functions;
#         * expansions «$var», «${var}», «${var:-default}», «${var+SET}»,
#           «${var#prefix}», «${var%suffix}», and «$( cmd )»;
#         * compound commands having a testable exit status, especially «case»;
#         * various built-in commands including «command», «set», and «ulimit».
#
#   Important for patching:
#
#   (2) This script targets any POSIX shell, so it avoids extensions provided
#       by Bash, Ksh, etc; in particular arrays are avoided.
#
#       The "traditional" practice of packing multiple parameters into a
#       space-separated string is a well documented source of bugs and failures;
#       so this is (mostly) avoided, by progressively accumulating options in
#       "$@", and eventually passing that to Java.
#
#       Where the inherited environment variables (DEFAULT_JVM_OPTS, JAVA_OPTS,
#       and GRADLE_OPTS) rely on word-splitting, this is performed explicitly;
#       this means that illegal characters and inadvertent patterns (such as
#       embedded double quotes) inside the value are treated as literal data
#       instead of triggering shell parser errors.
#
#   (3) When patching, please preserve the invariant that the content of
#       variables named CMD_* and JAVA_* are execve arguments (not subject to
#       further expansion), whereas the content of variables named OPT_* and
#       ARG_* are shell command line fragments (subject to further expansion).
#
#   (4) Code until the "End of script environment" section deals with
#       setting up the environment and the arguments, does redirections,
#       and generally prepares to launch Java. Do not add system
#       detection or other logic here, put it after the environment
#       section, in the "Gradle start" section.
#
#   (5) Since it is not known in advance whether the launch of Java will
#       require a tty for input (for example, if the build asks for
#       authentication credentials when connecting to a remote service),
#       it is not possible to know in advance whether 'gradle' should
#       wait for Java's termination, or immediately exit. The simplest
#       solution is to always wait for Java's termination, but use the
#       'exec' builtin to avoid creating a new process for Java. This
#       means that 'gradle' will always wait for Java's termination,
#       but without creating an intermediate shell process. This is
#       the best possible solution given the constraints.
#
##############################################################################

# Attempt to set APP_HOME

# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}  # leaves a trailing /; empty if no leading path
    [ -h "$app_path" ]
do
    ls=$( ls -ld "$app_path" )
    link=${ls#*' -> '}
    case $link in             #(
      /*)   app_path=$link ;; #(
      *)    app_path=$APP_HOME$link ;;
    esac
done

APP_HOME=$( cd "${APP_HOME:-./}" && pwd -P ) || exit

APP_NAME="Gradle"
APP_BASE_NAME=${0##*/}

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "$( uname )" in                #(
  CYGWIN* )         cygwin=true  ;; #(
  Darwin* )         darwin=true  ;; #(
  MSYS* | MINGW* )  msys=true    ;; #(
  NONSTOP* )        nonstop=true ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar


# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD=$JAVA_HOME/jre/sh/java
    else
        JAVACMD=$JAVA_HOME/bin/java
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    # Check for Java 17 specifically
    if [ -x "/usr/lib/jvm/java-17-openjdk-amd64/bin/java" ] ; then
        JAVACMD="/usr/lib/jvm/java-17-openjdk-amd64/bin/java"
        export JAVA_HOME="/usr/lib/jvm/java-17-openjdk-amd64"
    else
        JAVACMD=java
        which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
    case $MAX_FD in #(
      max*)
        MAX_FD=$( ulimit -H -n ) ||
            warn "Could not query maximum file descriptor limit"
    esac
    case $MAX_FD in  #(
      '' | soft) :;; #(
      *)
        ulimit -n "$MAX_FD" ||
            warn "Could not set maximum file descriptor limit to $MAX_FD"
    esac
fi

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the command line
#   * the main class name
#   * -classpath
#   * -D...appname settings
#   * --module-path (only if needed)
#   * DEFAULT_JVM_OPTS, JAVA_OPTS, and GRADLE_OPTS environment variables.

# For Cygwin or MSYS, switch paths to Windows format before running java
if "$cygwin" || "$msys" ; then
    APP_HOME=$( cygpath --path --mixed "$APP_HOME" )
    CLASSPATH=$( cygpath --path --mixed "$CLASSPATH" )

    JAVACMD=$( cygpath --unix "$JAVACMD" )

    # Now convert the arguments - kludge to limit ourselves to /bin/sh
    for arg do
        if
            case $arg in                                #(
              -*)   false ;;                            # don't mess with options #(
              /?*)  t=${arg#/} t=/${t%%/*}              # looks like a POSIX filepath
                    [ -e "$t" ] ;;                      #(
              *)    false ;;
            esac
        then
            arg=$( cygpath --path --ignore --mixed "$arg" )
        fi
        # Roll the args list around exactly as many times as the number of
        # args, so each arg winds up back in the position where it started, but
        # possibly modified.
        #
        # NB: a `for` loop captures its iteration list before it begins, so
        # changing the positional parameters here affects neither the number of
        # iterations, nor the values presented in `$arg`
        shift                   # remove old arg
        set -- "$@" "$arg"      # push replacement arg
    done
fi

# Collect all arguments for the java command;
#   * $DEFAULT_JVM_OPTS, $JAVA_OPTS, and $GRADLE_OPTS can contain fragments of
#     shell script including quotes and variable substitutions, so put them in
#     double quotes to make sure that they get re-expanded; and
#   * put everything else in single quotes, so that it's not re-expanded.

set -- \
        "-Dorg.gradle.appname=$APP_BASE_NAME" \
        -classpath "$CLASSPATH" \
        org.gradle.wrapper.GradleWrapperMain \
        "$@"

# Stop when "xargs" is not available.
if ! command -v xargs >/dev/null 2>&1
then
    warn "xargs is not available. Gradle will not work."
    exit 2
fi

# Use "xargs" to parse quoted args.
#
# With -n1 it outputs one arg per line, with the quotes and backslashes removed.
#
# In Bash we could simply go:
#
#   readarray ARGS < <( xargs -n1 <<<"$var" )
#
# but POSIX shell has neither of these features, so instead we must use a while loop
# that reads one line at a time.

# P.S. This assumes that none of the active codepage locales use a NUL byte within a
# single character. This is a safe assumption for the available POSIX locales on Linux,
# BSD, and macOS.
#
# P.P.S. This loop has complicated control flow because of the deferred read; the
# idea is to always do a read-ahead and keep the next value in $LINE, so we need to
# prime the loop, and also handle the last value after the loop exits.

# Read a line from stdin into $LINE, and exit the script if EOF is seen.
#
# The "head -n1" command will fail when it tries to read past EOF, so the
# "|| exit" is needed to prevent the script from dying. We still need to
# check the value of $LINE afterwards, because $LINE will be empty if
# either:
#
#   * a real EOF was read (in which case we should exit the loop); or
#   * a NUL byte was present in the input (in which case we should
#     continue the loop).
#
# The "|| exit" is needed to prevent the script from dying when the check
# is performed.
read_line () {
    IFS= read -r LINE || exit
}

# Process a line of input.
#
# This function uses $LINE as its input, rather than as a return value, because
# of the way shell variable scoping works. (Variables in the calling scope are
# only read-only.)
#
# The "|| exit" is needed to prevent the script from dying when the check is
# performed.
process_line () {
    case $LINE in
      '') exit ;;
      *)  set -- "$@" "$LINE" ;;
    esac
}

# Check if there's any input available before trying to read
if [ -t 0 ]; then
    # No input from stdin, skip the xargs processing
    :
else
    # Prime the read-ahead variable.
    read_line

    # Process all the lines.
    while :; do
        process_line
        read_line
    done

    # Process the last line.
    process_line
fi

# End of script environment. Begin Gradle start.

exec "$JAVACMD" "$@"